name: Functional Tests
description: Run Functional Tests
runs:
  using: "composite"
  steps:
    - name: Run functional test
      shell: bash
      run: |
        npm run docker npm ci
        docker-compose up -d
        bash tests/wait-kuzzle.sh
        npm run test