version: "3.9"

x-kuzzle-node: &kuzzle-node
    image: kuzzleio/kuzzle-runner:18
    command: ${DOCKER_COMMAND:-npm run dev}
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    volumes:
      - .:/var/app
    ports:
      - "7512:7512"
      - "9229:9229"
      - "1883:1883"
    depends_on:
      - redis
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__storageEngine__commonMapping__dynamic=true
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-none}
      # - DEBUG=${DEBUG:-kuzzle:*,-kuzzle:entry-point:protocols:websocket,-kuzzle:cluster:heartbeat}
      - kuzzle_cluster__minimumNodes=3

services:

  nginx:
    image: nginx:1.19-alpine
    container_name: kuzzle_nginx
    logging:
      driver: none
    depends_on:
      - kuzzle_node_1
      - kuzzle_node_2
      - kuzzle_node_3
    ports:
      - "7512:7512"
    volumes:
      - ./docker/nginx-dev:/etc/nginx/conf.d

  kuzzle_node_1:
    <<: *kuzzle-node
    container_name: kuzzle_node_1
    ports:
      - "17510:7512"

  kuzzle_node_2:
    <<: *kuzzle-node
    container_name: kuzzle_node_2
    ports:
      - "17511:7512"

  kuzzle_node_3:
    <<: *kuzzle-node
    container_name: kuzzle_node_3
    ports:
      - "17512:7512"

  redis:
    image: redis:6

  elasticsearch:
    image: kuzzleio/elasticsearch:7
    logging:
      driver: none
    ulimits:
      nofile: 65536
